### PR TITLE
Enable zulipbot build notifications.

### PR DESCRIPTION
**Pull request by synicalsyntax**
PRs labeled with the "travis updates" label will receive build notifications from zulipbot.

**Usage:**
Comment `@zulipbot label "travis updates"` on a pull request to label the pull request with the "travis updates" label. When the Travis build of the PR is complete, zulipbot will post a comment on the build status.

**Note:** It is highly recommended that a "travis updates" label be created in the repository (if else, zulipbot will automatically add a default-colored "travis updates" label).

### CODE REVIEW

**Comment by akashnimare** [comment]
@synicalsyntax thanks for the PR. Could you please wait until 17th May? I'm out of town.

**Comment by synicalsyntax** [comment]
Feel free to merge it whenever you're ready :)

**Comment by timabbott** [comment]
@akashnimare I assume you mean 17 March, right? :)

**Comment by akashnimare** [comment]
Oopss, yes :D

**Comment by akashnimare** [comment]
Merged. Thanks @synicalsyntax 😄

**Pull request merged**
