### PR TITLE
Created script to launch zulip-electron

### PR DESCRIPTION
**Pull request by GervaisdeM**
I spent a little time and updated my script to launch the electron version of the Zulip client.

Looking forward to harsh PR feedback.

### CODE REVIEW

**Comment by brainwane** [comment]
Thanks for the script, @GervaisdeM! Quick question just to make sure: this addresses #77?

If so: [Here's a guide to help you write commit messages](https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages) that are more consistent with our style (including mentioning what issue this pull request addresses), which makes it easier for us in the future -- when someone's trying to solve a new problem, if commit messages are all in the same format, it's easier to skim them in logs and quickly understand what's happening.

[Here are some tips on tidying your commit history, including changing your commit messages.](https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history) And when you update your code or your commit message, you can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and the changes will appear here. :)

**Comment by GervaisdeM** [comment]
A few things about this script that I'd like to point out and see if it requires any feedback.

1. It changes branch to master if a branch is not specified when calling the script (opinions on if this ok?)
2. It does not check if the branch specified exists or not. If the branch does not exist, then it just continues with whatever branch is currently checked out.
3. It does `git pull --rebase upstream master`. This assumes that you have set up an upstream remote. I think this is the Zulip recommended name. Opinion on this?

**Comment by akashnimare** [comment]
@GervaisdeM Thanks for working on this. I'm running this script from the root dir of zulip-electron repo and getting this - 

image

**Comment by GervaisdeM** [comment]
@akashnimare what are you running on? The script uses `realpath` to determine where the github repo is and that is failing on your machine. 

realpath exists on my Mac, but after some checking it seems that it was part of the `coreutils` that I must have installed at some point with brew. 
realpath exists on my CentOS 7 and Ubuntu 16 installs.

Regardless, I reworked the script to not require `realpath`

Does it work for you now?

**Comment by GervaisdeM** [comment]
@akashnimare 
Yeah, so my comments above.Number 3 refers to this issue.

Personally, I would have names that remote `zulip` as that is the convention that I normally use (using the organization name for the remote upstream repo.  I read the git part of the zulip docs and decided to call one of my remotes upstream as per the instructions there. The git pull is failing for you because you do not have a remote called `upstream`. 

I could search for a remote that matches for something like "git@github.com:zulip/zulip-electron.git" and tease out the remote name. That would also fail if the person has not added the zulip github repo. I am open to suggestions around how to solve this issue.

**Comment by akashnimare** [comment]
How about this?
```sh
prepareCheckout()
{
	cd $workingDir
	git checkout $myBranch
	git remote set-url upstream ssh://git@github.com/zulip/zulip-electron.git
	git reset --hard HEAD
	git pull origin master
}
```

**Comment by GervaisdeM** [comment]
Hi @akashnimare 

I did a little reading/checking
`git remote set-url upstream ssh://git@github.com/zulip/zulip-electron.git` will error if remote upstream doesn't exist.
`git reset --hard HEAD` might be a bit too harsh. I wouldn't want anyone to lose any work.

I changed the script again. Let me know what you think.

**Comment by akashnimare** [comment]
> git reset --hard HEAD might be a bit too harsh. I wouldn't want anyone to lose any work.

Yup. We could use `git stash` here then. Running your updated script throws this error - 

image

`git stash` fixes above problem.
```sh
prepareCheckout()
{
	git fetch $upstreamRemote
	git checkout $myBranch
	git stash
	git pull --rebase $upstreamRemote master
}
```
image

**Comment by GervaisdeM** [comment]
@akashnimare Git stash is definitely the way to go. Many more changes again. Let me know how it works for you and point out anything else that I may have missed.

**Comment by akashnimare** [comment]
Hey @GervaisdeM something is wrong 🤔 .

``` sh
./update.sh
fatal: Couldn't find remote ref upstream
Already on 'master'
Your branch is up-to-date with 'origin/master'.
fatal: Couldn't find remote ref upstream
Stashing uncommitted changes and doing a new git pull
No local changes to save
fatal: Couldn't find remote ref upstream
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Popping out uncommitted changes
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/akka/.nvm/versions/node/v6.3.1/bin/node" "/Users/akka/.nvm/versions/node/v6.3.1/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! file /Users/akka/dev/zulipwork/zulip-ex/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '<' at 19:1
npm ERR! <<<<<<< Updated upstream
npm ERR! ^
npm ERR! File: /Users/akka/dev/zulipwork/zulip-ex/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/akka/dev/zulipwork/zulip-ex/npm-debug.log
```

**Comment by GervaisdeM** [comment]
@akashnimare 
Did you rename the script to update.sh or copy it out of the zulip-electron folder?

There is no reference to upstream as a remote name anymore. It figures out what branch your remote branch for the official zulip-electron repo is named locally and uses that. The fact that you are seeing that error is odd to me.

Can you please:

1. `cd path-to/zulip-electron` (where path-to is the path to wherever you cloned the zulip-electron repo)
2. `git status`
3. `git log`
4 `ls -l`
5. `git --version`

I'd like to see what values are are getting for the above. Can you also let me know what OS you are running on.

**Comment by brainwane** [comment]
Right now, this is what I do to update all my repositories. It's a bash script:

~~~
#!/bin/bash

# update a bunch of Zulip git repositories

checkout_repo(){
    git checkout master
    git fetch upstream
    git rebase upstream/master
    git push origin master
    git checkout -
}
for repo in zulip zulip-android zulip-electron zulip.github.io
do
    pushd ${repo}
    checkout_repo
    popd
done
~~~

I think there are a few things in here that are not awesome (for instance, your script is better in that it has `git stash` in there to help avoid losing working directory changes), but I think your script could usefully borrow:
* using `git checkout -` instead of having to manually track the branch the user was on
* using `fetch` and `rebase` instead of `pull`
* including a `git push origin master` step to keep one's GitHub fork up to date

Hope this helps!

**Comment by GervaisdeM** [comment]
@brainwane 

* I didn't know about `git checkout -`, that is much simpler. 
* I don't know the subtleties between git rebase and git pull --rebase. I changed it as per your suggestion. 
* I'm not sure that it's a good idea to push changes to someone's master branch. For one thing, we may not be on the master branch as the script allows you to pull down an alternate branch.

Let me know what you think of it now.

**Comment by akashnimare** [comment]
@GervaisdeM really sorry for keeping this on hold as I was away for a while. Let me test it again.

**Comment by akashnimare** [comment]
@GervaisdeM I'm running the latest version of your script . After doing some minor changes in index.js, this is what I got -

```sh
./build.sh
M	app/main/index.js
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cannot rebase: You have unstaged changes.
Please commit or stash them.
Stashing uncommitted changes and doing a new git pull
Saved working directory and index state WIP on master: 9f70068 :bug: spellchecker path fixed
HEAD is now at 9f70068 :bug: spellchecker path fixed
Current branch master is up to date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Popping out uncommitted changes
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/main/index.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	build.sh

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (2416786a07eb5e2c601d288fe8e4299bbacdd185)

> Zulip-Desktop@0.4.2 start /Users/akka/dev/zulipwork/zulip-electron
> electron .
```

I think your script is failing to save uncommitted changes and also fails to rebase with master.

Here are the details you asked in https://github.com/zulip/zulip-electron/pull/80#issuecomment-255734631 -

* git status
```sh
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/main/index.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	build.sh

no changes added to commit (use "git add" and/or "git commit -a")
```
* git log
```sh
commit 9f70068184beff4e8a6d38b397096534988c8563
Author: Akash Nimare <akashnimare@users.noreply.github.com>
Date:   Tue Oct 25 03:08:59 2016 +0530

    :bug: spellchecker path fixed
and so on..
```

* ls -l
```sh
total 80
-rw-r--r--    1 akka  staff   1738 Nov  6 16:52 CONTRIBUTING.md
-rw-r--r--    1 akka  staff    130 Nov  6 16:52 ISSUE_TEMPLATE.md
-rw-r--r--    1 akka  staff  11357 Nov  6 16:52 LICENSE
-rw-r--r--    1 akka  staff   1808 Nov  6 16:52 README.md
drwxr-xr-x    5 akka  staff    170 Nov  6 16:52 app
-rw-r--r--    1 akka  staff    337 Nov  6 16:52 appveyor.yml
-rwxr-xr-x    1 akka  staff   1754 Nov  6 16:55 build.sh
-rw-r--r--    1 akka  staff    869 Nov  6 16:52 gulpfile.js
drwxr-xr-x  607 akka  staff  20638 Nov  6 17:05 node_modules
-rw-r--r--    1 akka  staff   1857 Nov  6 16:52 package.json
drwxr-xr-x    3 akka  staff    102 Nov  6 16:52 scripts
drwxr-xr-x    3 akka  staff    102 Nov  6 16:52 tests
```
* git --version
```sh
git version 2.9.2
```
* OS
``` sh
OS X EL Capitan (version 10.11.6)
```   
BTW does this script work for you while you have uncommitted changes?

**Comment by GervaisdeM** [comment]
@akashnimare 
I take it that you renamed the script to build.sh... I'm fine with that and will push with the new name.

It does work for me with uncommitted changes. It looks like it is working for you also.
You can see that it fails to successfully run the first git rebase $upstreamRemote/master command.
This triggers a git stash, sets a flag to do a git stash pop later and does a new git rebase.

Are you finding that the changes you made to index.js are no longer present after you run the script?

**Comment by GervaisdeM** [comment]
@akashnimare I'm not sure if this will work for you (it works for me on git repos where I can merge code, but fails with this PR), but you might want to try doing a hub checkout of my PR. `hub checkout https://github.com/zulip/zulip-electron/pull/80`

You might need to `brew install hub` first.

**Comment by akashnimare** [comment]
@GervaisdeM yeah, I tried it again and it's working as expected. Btw **build.sh** was just a random name 😄 . We should stick with **update.sh**. I'm merging it for now. Thanks a lot for working on this ✋ .

**Comment by akashnimare** [comment]
@brainwane It would be a nice to have this somewhere in [README.md](https://github.com/zulip/zulip-electron/blob/master/README.md) so that others can use it 😃 .

**Comment by brainwane** [comment]
@akashnimare Probably clear by now, but just to say so publicly: I don't have time to add that update-all-the-repositories script to the `README` but others should feel free to!

**Pull request merged**
