### PR TITLE
Minor Bug Fixes

### PR DESCRIPTION
**Pull request by Lplenka**
`zulip-electron:0.5.8`
`Operating System:Linux Mint 18`
Bugs:
1-There was a white screen appearing everytime you load the app.
2-No Title & Icon was present in `switch server` window tab in task bar
3-The `switch server` window remained open even after we have switched the server , multiple switching leads to many undisclosed `switch server` windows.
4-There was a white screen when you load `switch server` window or `About Zulip` window

Fixes-
1-The white screen doesn't appear any more in any window
2-Added Title & Icon for `switch server` window tab in task bar
3-Now `switch server` is closed automatically

### CODE REVIEW

**Comment by Lplenka** [comment]
Here is the gif with bugs:-
with_bugs


Here is the gif after bug fix
bug_fixed

All bugs i mentioned are fixed
Any suggestions are welcome

**Comment by brainwane** [comment]
Hi @Lplenka! Thanks for the pull request.

We appreciate it when a pull request has one logical change per commit -- [here are some tips on tidying your commit history](https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history) so you can improve your pull request.

For each commit, please write a descriptive commit message. [Here's a guide to help you write commit messages](https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages) that are more consistent with our style, which makes it easier for us in the future -- when someone's trying to solve a new problem, if commit messages are all in the same format, it's easier to skim them in logs and quickly understand what's happening.

And when you update your branch and your commit messages, you can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and the changes will appear here. :)

Thanks again!

**Comment by Lplenka** [comment]
Thank You @brainwane  for suggesting , I actually read somewhere to have a single commit for all changes before pull request.Guess was mistaken
Any ways I will take of the details and upadte pull request

**Comment by brainwane** [comment]
@Lplenka If you can let me know where you saw the "single commit for all changes" idea, that would be great, so I can fix any misunderstandings in our documentation! You might find https://zulip.readthedocs.io/en/latest/version-control.html#commit-discipline helpful:

> We follow the Git project’s own commit discipline practice of “Each commit is a minimal coherent idea”. This discipline takes a bit of work, but it makes it much easier for code reviewers to spot bugs, and makes the commit history a much more useful resource for developers trying to understand why the code works the way it does, which also helps a lot in preventing bugs....

**Comment by Lplenka** [comment]
@brainwane  I meant I heard it from one senior or might be read somewhere online days ago. Nothing wrong with zulip documentation. I just might have missed the commit part.

Thank you again for humble suggestions :smile:

**Comment by akashnimare** [comment]
@Lplenka thanks for the PR. Could you please wait until 17th? I'm out of town.

**Comment by Lplenka** [comment]
Yes sure, it seemed you were out of town, you were offline since days.
@akashnimare I will be happy to wait for few days to see my PR get accepted :smiley:

**Comment by akashnimare** [comment]
@Lplenka nicely done. Merged. Thanks 👌

**Comment by Lplenka** [comment]
@akashnimare I am glad you liked it :smile:

**Pull request merged**
