### PR TITLE
Added Clear-cache option in menu

### LINKED ISSUE #89: Add an option to clear the cache from menu items
Here is the api to do it - 
https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearcachecallback

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Closes #89 A clear cache option in menu has been added which clears the cache of the electron application.

### CODE REVIEW

**Comment by akashnimare** [comment]
@jajodiaraghav thanks for working on this. Two things -
1. Remove it from help menu and put it in file menu. Specifically [here](https://github.com/zulip/zulip-electron/blob/master/app/main/menu.js#L137) and [here](https://github.com/zulip/zulip-electron/blob/master/app/main/menu.js#L266).
2. I see no changes after clearing the cache. What does it do?

**Comment by jajodiaraghav** [comment]
@akashnimare 

> Remove it from help menu and put it in file menu. Specifically here and here.

Done

> I see no changes after clearing the cache. What does it do?

It opens a dialog which prompts with the message "Cache cleared".

**Comment by akashnimare** [comment]
And what happens once the cache is cleared? Does user gets logged out?

**Comment by jajodiaraghav** [comment]
No. Should it logout automatically after cache gets cleared?

**Comment by akashnimare** [comment]
Wait. Let me investigate what should ideally happens once the cache is cleared in electron.

**Comment by akashnimare** [comment]
Could you please fixed these linting errors - https://travis-ci.org/zulip/zulip-electron/jobs/189759542#L303

**Comment by jajodiaraghav** [comment]
Okay. I am working on it

**Comment by akashnimare** [comment]
You can test it with `npm run test`. We are using [XO](https://github.com/sindresorhus/xo) linter.

**Comment by akashnimare** [comment]
@jajodiaraghav cool. It works as expected. Basically this option deletes the temp. files present in `userData/Zulip/Cache` folder 😄  I'll merge it once you fix those linting errors.

**Comment by akashnimare** [comment]
@jajodiaraghav Merging 🚀

**Pull request merged**
