### PR TITLE
Remove node-json-db requirement, fixes #50

### LINKED ISSUE #50: Error opening Zulip darwin build
#### Summary

Zulip doesn't open when bundled as an application on osx.

#### Steps to reproduce

On OSX 10.10, create a new npm script in package.json:
`"build-osx": "electron-packager . --out=dist --platform=darwin --arch=x64 --
  app-version=$npm_package_version --asar --overwrite"`

then run `npm run-script build-osx`

one that finishes, `open dist/Zulip-darwin-x64/Zulip.app`

#### Expected behavior

Zulip starts with no error

#### Observed behavior

screen shot 2016-08-14 at 12 46 31 pm

#### Possible fixes

Just a guess, but maybe Electron doesn't have filesystem level access? Depending on what node-json-db is used for, localStorage might be enough.

### PR DESCRIPTION
**Pull request by jedahan**
Seems that electron doesn't play nice with node-json-db.
Might be a filesystem access thing.

I have no idea what i'm doing, but now I have a nice shiny Zulip.app in ~/Applications that works, so hooray!

### CODE REVIEW

**Comment by antifuchs** [comment]
I just checked out your pull request, and ran `npm run-script build-osx`. The resulting app sadly still displays an error (not the same one as before, though!)

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at set (/Users/asf/Hacks/zulip-electron/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/electron.asar/browser/api/web-contents.js:161:22)
    at EventEmitter.<anonymous> (/Users/asf/Hacks/zulip-electron/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/app.asar/app/main/index.js:211:17)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.<anonymous> (/Users/asf/Hacks/zulip-electron/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/electron.asar/browser/api/web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

I'll dig at this some, but maybe you can tell what this is about (:

**Comment by antifuchs** [comment]
It seems that `conf` is unset in the handler:

``` js
ipc.on('get-domain', function(e, domain) {
  e.returnValue = conf.get("domain");
});
```

To get my app build working, I simply replaced the call to `conf.get` with the constant for RC's zulip instance. Once that was set (I added it in Preferences to be safe), I could check out the unmodified code from this pull request and use the app as normal. Diagnosis: This doesn't yet handle the case where a new user has no preferences set yet.

Otherwise, this looks super good to me! I'm very excited to have an .app bundle that works, thanks so much!! ((:

**Comment by antifuchs** [comment]
`configstore` drops the configuration in `~/configstore/Zulip-Desktop.json` - that's not quite ideal on the mac, but I think it's still pretty tolerable (:

I just tried deleting this file & starting the app. While it only showed a blank window, there was no error and I could set a server with `Cmd-,` - this looks much better to me!

**Comment by akashnimare** [comment]
@jedahan @antifuchs thanks for working on this. I'm using `node-json-db` since it's easier to use and can handle db pretty easily. I'm not sure why you got https://github.com/zulip/zulip-electron/issues/50. Electron works fine with file systems.

**Comment by akashnimare** [comment]
@antifuchs @jedahan we have released v0.0.1-alpha with dmg and .app for OS X. You can install it here https://github.com/zulip/zulip-electron/releases . Let me know if it works for you.

**Comment by antifuchs** [comment]
I just downloaded the .zip version, and it works quite well! Starts up & launches with the right icon. The only (minor) thing is that OS X complains it's not code-signed. I guess that's expected, though!

**Comment by akashnimare** [comment]
@antifuchs yes it's coming in next release 🚀 .

**Comment by akashnimare** [comment]
@jedahan Thanks for working on this ✋ .

**Comment by akashnimare** [comment]
@antifuchs 
> I'm very excited to have an .app bundle that works.

Pushed this feature to master. Now you run create dmg, .app etc installers using `npm run dist` 😄

**Pull request closed without merging**
