### PR TITLE
Redesign the landing page to look more inline with brand design.

### PR DESCRIPTION
**Pull request by brockwhittaker**
This redesigns the landing page to incorporate the Zulip style guide.
This also adds two animations:

1. The error text slides down on error and back up when typing.
2. The form section shakes when there is invalid input for 0.5s.

New Landing Page

### CODE REVIEW

**Comment by Lplenka** [comment]
@brockwhittaker the page looks great! :+1: 

you should try running `npm run test`  to check travis errors.

Check this [Contributing.md](https://github.com/zulip/zulip-electron/blob/master/CONTRIBUTING.md) for not failing Travis checks next time. :smile:

**Comment by brockwhittaker** [comment]
I just fixed all mine but there's still ~25 errors that aren't mine that are present.

**Comment by Lplenka** [comment]
@brockwhittaker  happens with me too.
`npm run test` shows  JS Lint errors not directly linked with our contribution.
But all of them can be easily fixed. 

It's always better if our Pull Request has no JS Lint errors, It takes time to trace those small errors and fix them, but efforts are worth it. you won't ever fail in Travis builds :+1:

**Comment by akashnimare** [comment]
@brockwhittaker we could make it better :P but for now, this looks good. Merged. Thanks for working on this 🙏

**Pull request merged**
